### ISSUE TITLE
Node dependencies broken ?

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#121]
Hi,

When I'm making a `node` project, either **polka** or **express**, I have
~~~
Error: Failed to replace env in config: ${NPM_API_KEY}
    at /usr/lib/node_modules/npm/lib/config/core.js:417:13
    at String.replace (<anonymous>)
    at envReplace (/usr/lib/node_modules/npm/lib/config/core.js:413:12)
    at parseField (/usr/lib/node_modules/npm/lib/config/core.js:391:7)
    at /usr/lib/node_modules/npm/lib/config/core.js:334:17
    at Array.forEach (<anonymous>)
    at Conf.add (/usr/lib/node_modules/npm/lib/config/core.js:333:23)
    at ConfigChain.addString (/usr/lib/node_modules/npm/node_modules.bundled/config-chain/index.js:244:8)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:321:10)
    at /usr/lib/node_modules/npm/node_modules.bundled/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
TypeError: Cannot read property 'get' of undefined
    at errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at /usr/lib/node_modules/npm/bin/npm-cli.js:83:20
    at cb (/usr/lib/node_modules/npm/lib/npm.js:224:22)
    at /usr/lib/node_modules/npm/lib/npm.js:262:24
    at /usr/lib/node_modules/npm/lib/config/core.js:81:7
    at Array.forEach (<anonymous>)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:80:13)
    at Conf.f (/usr/lib/node_modules/npm/node_modules.bundled/once/once.js:25:25)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Conf.emit (events.js:211:7)
    at Conf.add (/usr/lib/node_modules/npm/lib/config/core.js:337:10)
    at ConfigChain.addString (/usr/lib/node_modules/npm/node_modules.bundled/config-chain/index.js:244:8)
    at Conf.<anonymous> (/usr/lib/node_modules/npm/lib/config/core.js:321:10)
    at /usr/lib/node_modules/npm/node_modules.bundled/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:511:3)
/usr/lib/node_modules/npm/lib/utils/error-handler.js:205
  if (npm.config.get('json')) {
                 ^

TypeError: Cannot read property 'get' of undefined
    at process.errorHandler (/usr/lib/node_modules/npm/lib/utils/error-handler.js:205:18)
    at emitOne (events.js:116:13)
    at process.emit (events.js:211:7)
    at process._fatalException (bootstrap_node.js:374:26)
~~~

@tbrand @lukeed How can I avoid that ?

Regards,

**Comment by lukeed** [comment]
This looks specific to your NPM install. Do you have issues installing or running anything else in the npm ecosystem?

If you look at the logs, it's all `/usr/lib/*/npm` based, and nothing to do with this repo.

**Comment by waghanza** [comment]
@lukeed exactly, I can not install anything using `npm`

I'm on 

+ NodeJS : `8.9.4`
+ NPM : 5.6.0

I'll try to see if bu reproduce on other version tomorrow

Also, I've seen that `npm` lock files are versionned, #122

**Comment by lukeed** [comment]
Your `npm` is installed incorrectly afaict. Pretty sure it should always be `/usr/local`. I'd remove everything you have now & follow [this guide](https://github.com/creationix/nvm#installation) from `nvm`, so that your future upgrade process is seamless.

**Comment by waghanza** [comment]
the same command work on **fedora** `26`, I was testing on **fedora** `27`

same version of **node** and **npm**

**Comment by waghanza** [comment]
@lukeed just have the same issue now/ removing my `~/.npm` folder and `~/.npmrc` file and it **works**.
