### ISSUE TITLE
japronto failure

### ISSUE THREAD

**Issue by waghanza** [tbrand/which_is_the_fastest#263]
Hi,

`japronto` implementation is failing. With the latest version of uvloop (`0.10.1`), I have

~~~python
Exception in callback UVTransport._call_connection_made
handle: <Handle UVTransport._call_connection_made>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 67, in uvloop.loop.Handle._run
  File "uvloop/handles/tcp.pyx", line 151, in uvloop.loop.TCPTransport._call_connection_made
  File "uvloop/handles/basetransport.pyx", line 156, in uvloop.loop.UVBaseTransport._call_connection_made
  File "uvloop/handles/basetransport.pyx", line 153, in uvloop.loop.UVBaseTransport._call_connection_made
SystemError: NULL result without error in PyObject_Call
~~~

@see https://github.com/squeaky-pl/japronto/issues/99

Regards,

**Comment by waghanza** [comment]
ping @squejly-pl

**Comment by waghanza** [comment]
@btegs ok, `japronto` seems promising. Is there any candidate for maintenance ?

**Comment by waghanza** [comment]
@btegs it seems to be a problem with  `uvloop`, not `japronto`, using **python** `3.6` fix everything

https://github.com/MagicStack/uvloop/issues/178

**Comment by btegs** [comment]
@waghanza - My issues were also with Python 3.6 on Ubuntu 18.04. I haven't tried Python 3.7 yet.

**Comment by ifplusor** [comment]
Because uvloop changed an method return type since 0.9.0. I fixed this in [
https://github.com/squeaky-pl/japronto/pull/133](url)
